version: "3.8"

services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/tflocal/Dockerfile
    volumes:
      - ./..:/workspace
    tty: true
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/tmp/localstack/data

volumes:
    localstack-data:
